import numpy as np
import cv2
from PIL import Image

class GenAIBridge:
    def __init__(self, api_key=""):
        self.api_key = api_key
        self.backend = "Google GenAI (Nano Banana)"
        
    def generate_inpaint(self, hdri_array, mask_array, prompt, neg_prompt=None, ckpt=None, steps=None, cfg=None):
        try:
            import sys
            import os
            import site
            user_site = site.getusersitepackages()
            if user_site not in sys.path:
                sys.path.append(user_site)
            
            # Force add user site to google namespace path if Nuke already imported google.protobuf
            if 'google' in sys.modules:
                google_user_path = os.path.join(user_site, 'google')
                if os.path.exists(google_user_path):
                    google_mod = sys.modules['google']
                    if hasattr(google_mod, '__path__') and google_user_path not in google_mod.__path__:
                        google_mod.__path__.append(google_user_path)
            
            from google import genai
            from google.genai import types
        except ImportError:
            import sys
            import os
            import subprocess
            try:
                print(f"[{self.backend}] Attempting to auto-install google-genai...")
                python_exe = sys.executable
                if "Nuke" in os.path.basename(python_exe) or "nuke" in os.path.basename(python_exe).lower():
                    python_exe = os.path.join(os.path.dirname(python_exe), "python.exe")
                
                subprocess.check_call([python_exe, "-m", "pip", "install", "--user", "google-genai"])
                
                if 'google' in sys.modules:
                    google_user_path = os.path.join(user_site, 'google')
                    if os.path.exists(google_user_path):
                        google_mod = sys.modules['google']
                        if hasattr(google_mod, '__path__') and google_user_path not in google_mod.__path__:
                            google_mod.__path__.append(google_user_path)
                            
                from google import genai
                from google.genai import types
            except Exception as e:
                python_exe = sys.executable
                if "Nuke" in os.path.basename(python_exe) or "nuke" in os.path.basename(python_exe).lower():
                    python_exe = os.path.join(os.path.dirname(python_exe), "python.exe")
                return hdri_array.copy(), f"google-genai module not installed.\nTo install it for this environment, run:\n\"{python_exe}\" -m pip install --user google-genai"
            
        try:
            print(f"[{self.backend}] Initializing GenAI with provided API key...")
            client = genai.Client(api_key=self.api_key)
            
            # Convert linear array to 8-bit sRGB for Nano Banana
            srgb_array = np.clip(hdri_array, 0, 1) ** (1.0 / 2.2)
            img_u8 = (srgb_array * 255).astype(np.uint8)
            mask_u8 = (np.clip(mask_array, 0, 1) * 255).astype(np.uint8)
            
            # Convert to PIL Images
            original_img = Image.fromarray(img_u8)
            mask_img = Image.fromarray(mask_u8)
            
            print(f"[{self.backend}] Prompt: '{prompt}'")
            
            response = client.models.generate_content(
                model="gemini-3.1-flash-image",
                contents=[
                    original_img, 
                    mask_img, 
                    prompt
                ]
            )
            
            if response.candidates and response.candidates[0].content.parts:
                for part in response.candidates[0].content.parts:
                    if part.inline_data:
                        # Extract the generated bytes
                        generated_bytes = part.inline_data.data
                        
                        # Decode the image back to numpy array
                        nparr = np.frombuffer(generated_bytes, np.uint8)
                        img_out = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
                        if img_out is not None:
                            rgb_out = cv2.cvtColor(img_out, cv2.COLOR_BGR2RGB).astype(np.float32) / 255.0
                            linear_out = rgb_out ** 2.2
                            
                            # Ensure exact dimension match
                            req_h, req_w = hdri_array.shape[:2]
                            if linear_out.shape[:2] != (req_h, req_w):
                                linear_out = cv2.resize(linear_out, (req_w, req_h), interpolation=cv2.INTER_LANCZOS4)
                                
                            print(f"[{self.backend}] Inpainting generation successful!")
                            return linear_out, None
                            
            return hdri_array.copy(), "Google GenAI API returned empty or invalid output."
            
        except Exception as e:
            print(f"[{self.backend}] Request failed: {e}")
            return hdri_array.copy(), f"Google GenAI API Request Failed:\n{e}"
