"""
Blender Python export templates for HDRI Match Plate.

Generates Blender-compatible Python scripts that recreate the calibrated
lighting setup from HDRI Match data. Supports World HDRI setup,
area lights from masks, and sun lights from extracted light sources.
"""
import numpy as np
import os
import json
import math


def export_blender_world_setup(hdri_path: str, calibration_state, export_dir: str) -> str:
    """
    Generate a Blender Python script that sets up the World environment
    with the calibrated HDRI and correct rotation/exposure.

    Args:
        hdri_path:          Path to the calibrated HDRI EXR file.
        calibration_state:  The pipeline's ImageState with calibration params.
        export_dir:         Directory to write the script to.

    Returns:
        Path to the generated Blender script.
    """
    st = calibration_state

    # Calculate color correction multipliers from temperature/tint
    temp = st.temperature
    tint = st.tint
    r_scale = max(0.01, 1.0 + temp + tint)
    g_scale = max(0.01, 1.0 - tint)
    b_scale = max(0.01, 1.0 - temp)
    lum = (r_scale + g_scale + b_scale) / 3.0
    r_scale /= lum
    g_scale /= lum
    b_scale /= lum

    yaw_radians = math.radians(st.hdri_yaw)
    ev_multiplier = 2.0 ** st.ev_offset

    script_lines = [
        "import bpy",
        "import math",
        "",
        "# ═══════════════════════════════════════════════════════",
        "# HDRI Match Plate — Blender World Setup",
        "# Generated by HDRI Match Plate Calibration Tool",
        "# ═══════════════════════════════════════════════════════",
        "",
        "# --- Clean existing World nodes ---",
        "world = bpy.context.scene.world",
        "if world is None:",
        "    world = bpy.data.worlds.new('HDRI_World')",
        "    bpy.context.scene.world = world",
        "world.use_nodes = True",
        "tree = world.node_tree",
        "tree.nodes.clear()",
        "",
        "# --- Create Environment Texture node ---",
        "env_node = tree.nodes.new('ShaderNodeTexEnvironment')",
        f"env_node.image = bpy.data.images.load(r'{hdri_path}')",
        "env_node.location = (-600, 300)",
        "",
        "# --- Rotation via Mapping + Texture Coordinate ---",
        "tex_coord = tree.nodes.new('ShaderNodeTexCoord')",
        "tex_coord.location = (-1000, 300)",
        "",
        "mapping = tree.nodes.new('ShaderNodeMapping')",
        "mapping.location = (-800, 300)",
        f"mapping.inputs['Rotation'].default_value = (0, 0, {yaw_radians})",
        "",
        "# --- Color Correction (Temperature/Tint as RGB Multiply) ---",
        "color_mix = tree.nodes.new('ShaderNodeMixRGB')",
        "color_mix.blend_type = 'MULTIPLY'",
        "color_mix.inputs[0].default_value = 1.0  # Factor",
        f"color_mix.inputs[2].default_value = ({r_scale}, {g_scale}, {b_scale}, 1.0)",
        "color_mix.location = (-200, 300)",
        "",
        "# --- Exposure (Multiply by EV) ---",
        "exposure_node = tree.nodes.new('ShaderNodeMath')",
        "exposure_node.operation = 'MULTIPLY'",
        f"exposure_node.inputs[1].default_value = {ev_multiplier}",
        "exposure_node.location = (0, 300)",
        "",
        "# --- Background and Output ---",
        "bg_node = tree.nodes.new('ShaderNodeBackground')",
        "bg_node.location = (200, 300)",
        "",
        "output_node = tree.nodes.new('ShaderNodeOutputWorld')",
        "output_node.location = (400, 300)",
        "",
        "# --- Wire up ---",
        "tree.links.new(tex_coord.outputs['Generated'], mapping.inputs['Vector'])",
        "tree.links.new(mapping.outputs['Vector'], env_node.inputs['Vector'])",
        "tree.links.new(env_node.outputs['Color'], color_mix.inputs[1])",
        "tree.links.new(color_mix.outputs['Color'], bg_node.inputs['Color'])",
        f"bg_node.inputs['Strength'].default_value = {ev_multiplier}",
        "tree.links.new(bg_node.outputs['Background'], output_node.inputs['Surface'])",
        "",
        "# --- Set Color Management ---",
        "bpy.context.scene.view_settings.view_transform = 'AgX'",
        "bpy.context.scene.view_settings.look = 'AgX - Base Contrast'",
        "",
        f"print('HDRI World setup complete: {os.path.basename(hdri_path)}')",
        f"print('  Rotation: {st.hdri_yaw:.1f} degrees')",
        f"print('  EV Offset: {st.ev_offset:+.2f}')",
        f"print('  Temperature: {temp:+.2f}  Tint: {tint:+.2f}')",
    ]

    script_path = os.path.join(export_dir, "blender_hdri_world.py")
    with open(script_path, 'w') as f:
        f.write("\n".join(script_lines))

    return script_path


def export_blender_lights(masks, hdri_array: np.ndarray, export_dir: str) -> str:
    """
    Generate a Blender Python script that creates Area Lights from
    HDRI mask regions, positioned on a sphere around the origin.

    Args:
        masks:       List of MaskLayer objects with rect, ev_offset, etc.
        hdri_array:  Linear float32 HDRI array (H, W, 3).
        export_dir:  Output directory.

    Returns:
        Path to the generated Blender script.
    """
    h, w = hdri_array.shape[:2]

    script_lines = [
        "import bpy",
        "import math",
        "from mathutils import Vector, Euler",
        "",
        "# ═══════════════════════════════════════════════════════",
        "# HDRI Match Plate — Blender Mask Lights",
        "# Generated by HDRI Match Plate Calibration Tool",
        "# ═══════════════════════════════════════════════════════",
        "",
        "# Create a collection for the lights",
        "coll_name = 'HDRI_Match_Lights'",
        "if coll_name not in bpy.data.collections:",
        "    coll = bpy.data.collections.new(coll_name)",
        "    bpy.context.scene.collection.children.link(coll)",
        "else:",
        "    coll = bpy.data.collections[coll_name]",
        "",
    ]

    for i, mask in enumerate(masks):
        if mask.rect is None:
            continue

        nx1, ny1, nx2, ny2 = mask.rect
        cx = (nx1 + nx2) / 2.0
        cy = (ny1 + ny2) / 2.0

        # Spherical coordinates
        theta = (cx * 2.0 * math.pi) - math.pi
        phi = (0.5 - cy) * math.pi

        dir_x = math.cos(phi) * math.sin(theta)
        dir_y = math.sin(phi)
        dir_z = math.cos(phi) * math.cos(theta)

        # Light dimensions (approximate)
        width_rad = (nx2 - nx1) * 2.0 * math.pi
        height_rad = (ny2 - ny1) * math.pi
        radius = 100.0
        light_width = max(width_rad * radius, 0.1)
        light_height = max(height_rad * radius, 0.1)

        # Sample average color from the mask region
        sx1, sx2 = max(0, int(nx1 * w)), min(w, int(nx2 * w))
        sy1, sy2 = max(0, int(ny1 * h)), min(h, int(ny2 * h))
        if sx2 > sx1 and sy2 > sy1:
            roi = hdri_array[sy1:sy2, sx1:sx2, :3]
            avg_color = roi.mean(axis=(0, 1)).tolist()
        else:
            avg_color = [1.0, 1.0, 1.0]

        # Normalize color and compute intensity
        max_c = max(avg_color)
        if max_c > 0:
            norm_color = [c / max_c for c in avg_color]
            intensity = max_c
        else:
            norm_color = [1.0, 1.0, 1.0]
            intensity = 1.0

        # EV adjustment
        ev_mult = 2.0 ** mask.ev_offset
        energy = intensity * ev_mult * 1000.0  # Blender uses watts

        safe_name = "".join(c if c.isalnum() else "_" for c in mask.name)
        if not safe_name:
            safe_name = f"Light_{i}"

        script_lines.extend([
            f"# --- {mask.name} ---",
            f"bpy.ops.object.light_add(type='AREA', location=({dir_x * radius}, {dir_z * radius}, {dir_y * radius}))",
            f"light_obj = bpy.context.active_object",
            f"light_obj.name = '{safe_name}'",
            f"light_obj.data.name = '{safe_name}_data'",
            f"light_obj.data.shape = 'RECTANGLE'",
            f"light_obj.data.size = {light_width}",
            f"light_obj.data.size_y = {light_height}",
            f"light_obj.data.energy = {energy:.2f}",
            f"light_obj.data.color = ({norm_color[0]:.4f}, {norm_color[1]:.4f}, {norm_color[2]:.4f})",
            "",
            f"# Point light at origin",
            f"direction = Vector(({dir_x * radius}, {dir_z * radius}, {dir_y * radius})) * -1",
            f"light_obj.rotation_euler = direction.to_track_quat('-Z', 'Y').to_euler()",
            "",
            f"# Move to collection",
            f"for c in light_obj.users_collection:",
            f"    c.objects.unlink(light_obj)",
            f"coll.objects.link(light_obj)",
            "",
        ])

    script_lines.append("print('Blender mask lights created successfully!')")

    script_path = os.path.join(export_dir, "blender_mask_lights.py")
    with open(script_path, 'w') as f:
        f.write("\n".join(script_lines))

    return script_path


def export_blender_sun(sun_data: dict, export_dir: str) -> str:
    """
    Generate a Blender Python script that creates a Sun light
    from extracted HDRI sun data.

    Args:
        sun_data:    Dict with 'direction_vector', 'peak_ev', 'color_rgb'.
        export_dir:  Output directory.

    Returns:
        Path to the generated script.
    """
    dir_x, dir_y, dir_z = sun_data["direction_vector"]
    color = sun_data.get("color_rgb", [1.0, 1.0, 1.0])
    max_c = max(color)
    if max_c > 0:
        norm_color = [c / max_c for c in color]
    else:
        norm_color = [1.0, 1.0, 1.0]

    # Blender sun energy (approximate from EV)
    energy = min(sun_data.get("peak_ev", 10.0), 20.0)

    script_lines = [
        "import bpy",
        "from mathutils import Vector",
        "",
        "# ═══════════════════════════════════════════════════════",
        "# HDRI Match Plate — Blender Sun Light",
        "# Generated by HDRI Match Plate Calibration Tool",
        "# ═══════════════════════════════════════════════════════",
        "",
        "bpy.ops.object.light_add(type='SUN', location=(0, 0, 10))",
        "sun = bpy.context.active_object",
        "sun.name = 'HDRI_Match_Sun'",
        "sun.data.name = 'HDRI_Match_Sun_data'",
        f"sun.data.energy = {energy:.2f}",
        f"sun.data.color = ({norm_color[0]:.4f}, {norm_color[1]:.4f}, {norm_color[2]:.4f})",
        "",
        f"# Point sun in the correct direction (Blender: Y-forward, Z-up)",
        f"direction = Vector(({dir_x}, {dir_z}, {dir_y}))",
        f"sun.rotation_euler = (-direction).to_track_quat('-Z', 'Y').to_euler()",
        "",
        f"print('Sun light created at azimuth={sun_data.get('azimuth_deg', 0):.1f}° "
        f"elevation={sun_data.get('elevation_deg', 0):.1f}°')",
    ]

    script_path = os.path.join(export_dir, "blender_sun_light.py")
    with open(script_path, 'w') as f:
        f.write("\n".join(script_lines))

    return script_path


def export_cg_lights_blender(light_params: dict, export_path: str) -> str:
    """
    Generate a Blender Python script that applies CG light match
    parameters (EV, temperature, tint) to existing Blender lights
    by fuzzy name matching.

    Args:
        light_params:  Dict of {light_name: {ev, temp, tint, color}}.
        export_path:   Path to write the JSON file.

    Returns:
        Path to the generated Blender script.
    """
    # Clean up names (strip 'C_' prefix)
    cleaned = {}
    for k, v in light_params.items():
        new_key = k.lower()
        if new_key.startswith("c_"):
            new_key = new_key[2:]
        cleaned[new_key] = v

    # Write JSON
    with open(export_path, 'w') as f:
        json.dump(cleaned, f, indent=4)

    script_path = os.path.splitext(export_path)[0] + "_blender.py"
    script_lines = [
        "import bpy",
        "import json",
        "import math",
        "",
        "# ═══════════════════════════════════════════════════════",
        "# HDRI Match Plate — Blender CG Light Match",
        "# Generated by HDRI Match Plate Calibration Tool",
        "# ═══════════════════════════════════════════════════════",
        "",
        f"json_path = r'{export_path}'",
        "with open(json_path, 'r') as f:",
        "    light_data = json.load(f)",
        "",
        "matched_count = 0",
        "for obj in bpy.data.objects:",
        "    if obj.type != 'LIGHT':",
        "        continue",
        "    name = obj.name.lower()",
        "    matching_keys = [k for k in light_data.keys() if k.endswith(name) or name in k]",
        "    if not matching_keys:",
        "        continue",
        "",
        "    params = light_data[matching_keys[0]]",
        "    ev = params.get('ev', 0.0)",
        "    temp = params.get('temp', 0.0)",
        "    tint = params.get('tint', 0.0)",
        "    explicit_color = params.get('color', [1.0, 1.0, 1.0])",
        "",
        "    # Apply EV offset",
        "    obj.data.energy *= (2.0 ** ev)",
        "",
        "    # Compute WB color multiplier",
        "    r_scale = max(0.01, 1.0 + temp + tint)",
        "    g_scale = max(0.01, 1.0 - tint)",
        "    b_scale = max(0.01, 1.0 - temp)",
        "    lum = (r_scale + g_scale + b_scale) / 3.0",
        "    wb = (r_scale/lum, g_scale/lum, b_scale/lum)",
        "",
        "    obj.data.color = (",
        "        obj.data.color[0] * wb[0] * explicit_color[0],",
        "        obj.data.color[1] * wb[1] * explicit_color[1],",
        "        obj.data.color[2] * wb[2] * explicit_color[2],",
        "    )",
        "    matched_count += 1",
        "    print(f'  Updated: {obj.name}  EV={ev:+.2f}  Temp={temp:+.2f}  Tint={tint:+.2f}')",
        "",
        "print(f'Successfully updated {matched_count} Blender lights from HDRI Match Plate!')",
    ]

    with open(script_path, 'w') as f:
        f.write("\n".join(script_lines))

    return script_path
